name: Node.js Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  run-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Start server (once)
        run: |
          node index.js &
          sleep 5
          curl -f http://localhost:${{ secrets.PORT }}/api-docs || exit 1
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PORT: ${{ secrets.PORT }}

  auto-merge:
    if: github.event.pull_request.merged == false && github.event.pull_request.base.ref == 'develop'
    needs: run-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable auto-merge for PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.AUTO_MERGE_TOKEN }}  # Use the PAT here for auto-merge
          repository: ${{ github.repository }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: merge
